### ISSUE TITLE
Support for SPAT/MAP messages? PER decoding?

### ISSUE THREAD

**Issue by karthikdevarakonda93** [JonathanWilbur/asn1-d#2]
Will there be a future support for SPAT/MAP messages in PER decoding.?
This is for compiling J2735-2016 asn specification.  https://www.sae.org/standards/content/j2735_201603/

**Comment by JonathanWilbur** [comment]
I had not planned on it, because I have ceased all new non-bug-related development on this library, but I may in the near future, if I can do so easily enough. Two questions for you, if you would like me to:

1. Do I have to implement _all_ of the ASN.1 PER types? Would implementing PER-encoding and decoding of only `INTEGER`, `BOOLEAN`, and `UTF8String`, for instance, be sufficient for your purposes? What subset of PER would be sufficient? I ask because I do not have access to the ASN.1 specifications, and I do not want to pay $80 just to read it.
2. Does this project have to be in D? I have a much better [ASN.1 library in TypeScript](https://github.com/JonathanWilbur/asn1-ts), though that one also does not support PER. I might be more inclined to add PER to the TypeScript library.

Also, in the somewhat near future, I expect to implement either a Rust or Go version (I haven't decided which). That may be of interest to you.

**Comment by karthikdevarakonda93** [comment]
Thank you for the response. To answer your questions, 1) Yeah, I don't think that would be sufficient for my purposes. I would require the other subsets like signal groups, movement states etc. So this would be a big leap.
2) Interesting stuff. I can take a look at it.

Thanks again.
